### ISSUE TITLE
Unable to forward TiProxy port to 6000

### ISSUE THREAD

**Issue by yaoyinnan** [pingcap/tiproxy#318]
### 1. Minimal reproduce step (Required)

1. Generate a self-signed certificate, which is used for the token-based authentication between TiDB and TiProxy.

```
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout key.pem -out cert.pem -subj "/CN=example.com"
```

2. Create secrets for session token signing certs.

```
$ kubectl create secret generic basic-sess -n $NAMESPACE --from-file=crt=cert.pem --from-file=key=key.pem
```

3. Use TiDB Operator to deploy TiDB cluster on K8s, the configuration file is as follows:

```
apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: auto-scaling-demo
spec:
  version: v6.5.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 3
    requests:
      storage: "10Gi"
    config: |
      [pd-server]
        metric-storage = "http://auto-scaling-demo-prometheus:9090/"
    storageClassName: shared-ssd-storage
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    replicas: 3
    requests:
      cpu: "1"
      storage: "100Gi"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "8Gi"
    config: {}
    storageClassName: shared-ssd-storage
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    service:
      type: ClusterIP
    config: |
      graceful-wait-before-shutdown=10
      [security]
        session-token-signing-cert = "/var/sess/cert.pem"
        session-token-signing-key = "/var/sess/key.pem"
    additionalVolumes:
    - name: "sess"
      secret:
        secretName: basic-sess
        items:
        - key: crt
          path: cert.pem
        - key: key
          path: key.pem
    additionalVolumeMounts:
    - name: "sess"
      mountPath: /var/sess
      readOnly: false
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "8Gi"
    storageClassName: shared-ssd-storage
  tiproxy:
    replicas: 1
    baseImage: tiproxy:latest
```

4. After starting the cluster, set port forwarding to forward 6000 to local port 6000:

```
$ kubectl port-forward -n tidb-cluster-autoscale svc/auto-scaling-demo-tiproxy 6000:6000 &
$ mysql -h127.0.0.1 -uroot -P6000
```

### 2. What did you expect to see? (Required)

The port forwarding is successful and the proxy can be accessed by connecting to port 6000.

### 3. What did you see instead (Required)

Unable to forward successfully, error:
```
error: timed out waiting for the condition
```

Pods information:

I found no tiproxy pod started.

```
$ kubectl get pods -n tidb-cluster-autoscale
NAME                                           READY   STATUS    RESTARTS      AGE
auto-scaling-demo-discovery-8699fbd4f6-6fl4d   1/1     Running   0             60m
auto-scaling-demo-monitor-0                    4/4     Running   0             60m
auto-scaling-demo-pd-0                         1/1     Running   0             60m
auto-scaling-demo-pd-1                         1/1     Running   0             60m
auto-scaling-demo-pd-2                         1/1     Running   1 (60m ago)   60m
auto-scaling-demo-tidb-0                       2/2     Running   0             60m
auto-scaling-demo-tikv-0                       1/1     Running   0             60m
auto-scaling-demo-tikv-1                       1/1     Running   0             60m
auto-scaling-demo-tikv-2                       1/1     Running   0             60m
```

Services information:
```
$ kubectl get svc -n tidb-cluster-autoscale
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
auto-scaling-demo-discovery          ClusterIP   10.103.228.94    <none>        10261/TCP,10262/TCP             61m
auto-scaling-demo-grafana            ClusterIP   10.98.22.74      <none>        3000/TCP                        61m
auto-scaling-demo-monitor-reloader   ClusterIP   10.102.86.102    <none>        9089/TCP                        61m
auto-scaling-demo-pd                 ClusterIP   10.106.253.147   <none>        2379/TCP                        61m
auto-scaling-demo-pd-peer            ClusterIP   None             <none>        2380/TCP,2379/TCP               61m
auto-scaling-demo-prometheus         ClusterIP   10.104.46.154    <none>        9090/TCP                        61m
auto-scaling-demo-tidb               ClusterIP   10.110.94.3      <none>        4000/TCP,10080/TCP              60m
auto-scaling-demo-tidb-peer          ClusterIP   None             <none>        10080/TCP                       60m
auto-scaling-demo-tikv-peer          ClusterIP   None             <none>        20160/TCP                       61m
auto-scaling-demo-tiproxy            NodePort    10.108.158.43    <none>        3080:31341/TCP,6000:30015/TCP   61m
auto-scaling-demo-tiproxy-peer       ClusterIP   None             <none>        3080/TCP,3081/TCP               61m
```

Endpoints information:

I found that auto-scaling-demo-tiproxy has no endpoints.

```
$ kubectl get endpoints -n tidb-cluster-autoscale
NAME                                 ENDPOINTS                                                        AGE
auto-scaling-demo-discovery          10.244.2.73:10261,10.244.2.73:10262                              62m
auto-scaling-demo-grafana            10.244.1.86:3000                                                 61m
auto-scaling-demo-monitor-reloader   10.244.1.86:9089                                                 61m
auto-scaling-demo-pd                 10.244.1.84:2379,10.244.1.85:2379,10.244.2.74:2379               62m
auto-scaling-demo-pd-peer            10.244.1.84:2379,10.244.1.85:2379,10.244.2.74:2379 + 3 more...   62m
auto-scaling-demo-prometheus         10.244.1.86:9090                                                 61m
auto-scaling-demo-tidb               10.244.1.88:10080,10.244.1.88:4000                               61m
auto-scaling-demo-tidb-peer          10.244.1.88:10080                                                61m
auto-scaling-demo-tikv-peer          10.244.1.87:20160,10.244.2.75:20160,10.244.2.76:20160            61m
auto-scaling-demo-tiproxy            <none>                                                           61m
auto-scaling-demo-tiproxy-peer       <none>                                                           61m
```

How can I troubleshoot the error? Please help and guide me, thanks.

And is there an official TiProxy mirror?

### 4. What is your version? (Required)

tiproxy version: github.com/pingcap/TiProxy's latest branch make && make docker image.
tidb version: v6.5.0
tidb-operator version: v1.4.4
